site_name: TotalProd
theme:
  name: material
  language: 'pt'
  logo: 'https://totalprod.com.br/src-app/images/iconbg.svg'
extra_css:
    - 'css/extra_css.css'
    - 'css/lightbox.css'
nav: 
    - Home: index.md
    - Assinatura: assinatura.md
    - Financeiro: financeiro.md
    - Gerencial: gerencial.md
        

extra_javascript: 
  - 'javascripts/jquery.min.js'
  - 'javascripts/lightbox.js'
  - 'javascripts/extra.js'
  
plugins:
    - search:
        lang: pt
     
