site_name: TotalProd
theme: 
  name: material

extra_css:
    - 'css/extra_css.css'
    - 'css/lightbox.css'
nav: 
    - Home: index.md
    - Assinatura: assinatura.md
    - Financeiro: financeiro.md
    - Gerencial: gerencial.md
        
repo_url: https://totalprod.com.br

extra_javascript: 
  - 'javascripts/jquery.min.js'
  - 'javascripts/lightbox.js'
  - 'javascripts/extra.js'
