site_name: TotalProd
site_description: documentação do projeto TotalProd
site_author: Gabriel Duarte
  
repo_url: https://totalprod.com.br/ 
edit_uri : " "

theme:
  name: material
  language: 'pt'
  logo: 'https://totalprod.com.br/src-app/images/iconbg.svg'
  favicon: 'assets/images/favicon.ico'

extra_css:
    - 'css/extra_css.css'
    - 'css/lightbox.css'

nav: 
    - Home: index.md
    - Assinatura: assinatura.md
    - Financeiro: financeiro.md
    - Gerencial: gerencial.md
        

extra_javascript: 
  - 'javascripts/jquery.min.js'
  - 'javascripts/lightbox.js'
  - 'javascripts/extra.js'
  
copyright: direitos autorais e cópia; 2019<a href="https://github.com/bielduarte"> Gabriel Duarte</a>
google_analytics: ['UA-27795084-5', 'mkdocs.org']

